services:
  - type: web
    name: hris-demo
    runtime: docker
    repo: https://github.com/Justdave06/HRIS_Demo
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: array
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: stderr
      - key: APP_MAINTENANCE_STORE
        value: array
